name: openai_dart_dio
description: openai dart type safe library use dio
version: 2.0.0
homepage: https://github.com/wilinz/openai_dart_dio
repository: https://github.com/wilinz/openai_dart_dio

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dio: ^5.3.3
  fetch_client: ^1.0.2
  native_dio_adapter: ^1.1.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  copy_with_extension: ^6.0.1
  equatable: ^2.0.5
  autoequal: ^0.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  json5_model: ^4.1.0
  copy_with_extension_gen: ^6.0.1
  autoequal_gen: ^0.9.5

index_generator:
  exclude:
    - '**.g.dart'
  # Define the paths of the folders in which to generate the index files
  libraries:
    - directory_path: lib